/* -*- Mode: Java; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* vim: set shiftwidth=2 tabstop=2 autoindent cindent expandtab: */

//Please keep the owner names consistent with phonebook names

var OWNERS = {
  "Add-on": "Mike Lien",
  "Bluetooth": "Teri Wen",
  "Bluetooth PTS": "Teri Wen",
  "Gaia::Calendar": "Edward Chen",
  "Gaia::Camera": "",
  "Gaia::Clock": "Edward Chen",
  "Gaia::Contacts": "Eric Chang",
  "Gaia::Cost Control": "Shing Lyu",
  "Gaia::Dialer": "Eric Chang",
  "Gaia::E-Mail": "Edward Chen",
  "Gaia::FTU": "",
  "Gaia::FMRadio": "",
  "Gaia::Gallery": "",
  "Gaia::Homescreen": "Hermes Cheng",
  "Gaia::Keyboard": "Gerry Chang",
  "Gaia::Music": "",
  "Gaia::Ringtones": "Alison Shiue",
  "Gaia::Search": "",
  "Gaia::Settings": "",
  "Gaia::SMS": "Eric Chang",
  "Gaia::System": "",
  "Gaia::System::Lockscreen": "Gerry Chang",
  "Gaia::System::Window Mgmt": "",
  "Gaia::Video": "",
  "MTBF-Nexus5L": "Alison Shiue",
  "MTP/UMS": "Alison Shiue",
  "New Homescreen": "Teri Wen",
  "NFC": "Alison Shiue",
  "OTA": "Gerry Chang",
  "Pin the Web": "Alison Shiue",
  "Private Browsing": "Alison Shiue",
  "Privacy Panel": "Gerry Chang",
  "RIL": "Eric Chang",
  "Storage": "Alison Shiue",
  "SystemPlatform": "Gerry Chang",
  "Telemetry": "Iris Hsiao",
  "Text Selection": "*",
  "Tracking Protection": "Alison Shiue",
  "Wifi": "Gerry Chang"
};
